### ISSUE TITLE
Uploading a Contract to Juno Testnet

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#76]
Getting the following error when trying to upload to Juno: Invalid string. Length must be a multiple of 4
<img width="1036" alt="Screen Shot 2023-07-19 at 5 16 10 PM" src="https://github.com/andromedaprotocol/andromeda.js/assets/90905690/552089f1-718c-4986-a13f-b24791e21b23">

**Comment by leifasorensen** [comment]
There was a problem originating with some alterations to the deprecation of broadcast mode `block` from the cosmos-sdk which conflicted with Andromeda.js setup. See PR 12659  from cosmos/cosmos-sdk for reference. We have since made the correct adjustments to resolve this issue.

This issue has been resolved and I will be closing this issue.
